<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4abizgb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4abizgb/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4abizgb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4abizgb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4abizgb\appProdProjectContainer(array(
    'container.build_hash' => '4abizgb',
    'container.build_id' => '78b152ca',
    'container.build_time' => 1530864022,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4abizgb');
